# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bitchhunter3000/projects/cpp_vel_model

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bitchhunter3000/projects/cpp_vel_model

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bitchhunter3000/projects/cpp_vel_model/CMakeFiles /home/bitchhunter3000/projects/cpp_vel_model/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bitchhunter3000/projects/cpp_vel_model/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named velocity-model

# Build rule for target.
velocity-model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 velocity-model
.PHONY : velocity-model

# fast build rule for target.
velocity-model/fast:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/build
.PHONY : velocity-model/fast

src/Particle.o: src/Particle.cpp.o

.PHONY : src/Particle.o

# target to build an object file
src/Particle.cpp.o:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/Particle.cpp.o
.PHONY : src/Particle.cpp.o

src/Particle.i: src/Particle.cpp.i

.PHONY : src/Particle.i

# target to preprocess a source file
src/Particle.cpp.i:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/Particle.cpp.i
.PHONY : src/Particle.cpp.i

src/Particle.s: src/Particle.cpp.s

.PHONY : src/Particle.s

# target to generate assembly for a file
src/Particle.cpp.s:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/Particle.cpp.s
.PHONY : src/Particle.cpp.s

src/Station.o: src/Station.cpp.o

.PHONY : src/Station.o

# target to build an object file
src/Station.cpp.o:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/Station.cpp.o
.PHONY : src/Station.cpp.o

src/Station.i: src/Station.cpp.i

.PHONY : src/Station.i

# target to preprocess a source file
src/Station.cpp.i:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/Station.cpp.i
.PHONY : src/Station.cpp.i

src/Station.s: src/Station.cpp.s

.PHONY : src/Station.s

# target to generate assembly for a file
src/Station.cpp.s:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/Station.cpp.s
.PHONY : src/Station.cpp.s

src/TimeGraph.o: src/TimeGraph.cpp.o

.PHONY : src/TimeGraph.o

# target to build an object file
src/TimeGraph.cpp.o:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/TimeGraph.cpp.o
.PHONY : src/TimeGraph.cpp.o

src/TimeGraph.i: src/TimeGraph.cpp.i

.PHONY : src/TimeGraph.i

# target to preprocess a source file
src/TimeGraph.cpp.i:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/TimeGraph.cpp.i
.PHONY : src/TimeGraph.cpp.i

src/TimeGraph.s: src/TimeGraph.cpp.s

.PHONY : src/TimeGraph.s

# target to generate assembly for a file
src/TimeGraph.cpp.s:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/TimeGraph.cpp.s
.PHONY : src/TimeGraph.cpp.s

src/VelocityModel.o: src/VelocityModel.cpp.o

.PHONY : src/VelocityModel.o

# target to build an object file
src/VelocityModel.cpp.o:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/VelocityModel.cpp.o
.PHONY : src/VelocityModel.cpp.o

src/VelocityModel.i: src/VelocityModel.cpp.i

.PHONY : src/VelocityModel.i

# target to preprocess a source file
src/VelocityModel.cpp.i:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/VelocityModel.cpp.i
.PHONY : src/VelocityModel.cpp.i

src/VelocityModel.s: src/VelocityModel.cpp.s

.PHONY : src/VelocityModel.s

# target to generate assembly for a file
src/VelocityModel.cpp.s:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/src/VelocityModel.cpp.s
.PHONY : src/VelocityModel.cpp.s

velocity-model.o: velocity-model.cxx.o

.PHONY : velocity-model.o

# target to build an object file
velocity-model.cxx.o:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/velocity-model.cxx.o
.PHONY : velocity-model.cxx.o

velocity-model.i: velocity-model.cxx.i

.PHONY : velocity-model.i

# target to preprocess a source file
velocity-model.cxx.i:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/velocity-model.cxx.i
.PHONY : velocity-model.cxx.i

velocity-model.s: velocity-model.cxx.s

.PHONY : velocity-model.s

# target to generate assembly for a file
velocity-model.cxx.s:
	$(MAKE) -f CMakeFiles/velocity-model.dir/build.make CMakeFiles/velocity-model.dir/velocity-model.cxx.s
.PHONY : velocity-model.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... velocity-model"
	@echo "... src/Particle.o"
	@echo "... src/Particle.i"
	@echo "... src/Particle.s"
	@echo "... src/Station.o"
	@echo "... src/Station.i"
	@echo "... src/Station.s"
	@echo "... src/TimeGraph.o"
	@echo "... src/TimeGraph.i"
	@echo "... src/TimeGraph.s"
	@echo "... src/VelocityModel.o"
	@echo "... src/VelocityModel.i"
	@echo "... src/VelocityModel.s"
	@echo "... velocity-model.o"
	@echo "... velocity-model.i"
	@echo "... velocity-model.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

